### ISSUE TITLE
 json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64

### ISSUE THREAD

**Issue by PS6** [hashicorp/packer-plugin-cloudstack#30]
#### Overview of the Issue
Machine is build, but template creation not started as the packer process stops with error
Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64

The error is not correct as the instance is created !

#### Reproduction Steps
Always the same ...
Have not been able to get further

### Plugin and Packer version
2022/01/07 11:36:51 [INFO] Packer version: 1.7.8 [go1.17.2 linux amd64]
2022/01/07 11:36:51 [TRACE] discovering plugins in /usr/bin
2022/01/07 11:36:51 [TRACE] discovering plugins in /home/packer/.config/packer/plugins
2022/01/07 11:36:51 [TRACE] discovering plugins in .
2022/01/07 11:36:51 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/01/07 11:36:51 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/packer/.packerconfig
2022/01/07 11:36:51 [WARN] Config file doesn't exist: /home/packer/.packerconfig
2022/01/07 11:36:51 [INFO] Setting cache directory: /home/packer/.cache/packer
2022/01/07 11:36:51 machine readable: version []string{"1.7.8"}
2022/01/07 11:36:51 machine readable: version-prelease []string{""}
2022/01/07 11:36:51 machine readable: version-commit []string{"cc7374e3f"}
Packer v1.7.8
2022/01/07 11:36:51 [INFO] (telemetry) Finalizing.
2022/01/07 11:36:51 waiting for all plugin processes to complete...

### Simplified Packer Buildfile
packer {
  required_plugins {
    cloudstack = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/cloudstack"
    }
  }
}

source "cloudstack" "autogenerated_1" {
  api_key                   = "XXX"
  api_url                   = "XXX"
  disk_offering             = "Small 2"
  network                   = "rtd-mote"
  pause_before_connecting   = "15m"
  public_ip_address         = "XXX"
  public_port               = "XXX"
  secret_key                = "XXX"
  service_offering          = "VM 1 vCPU - 4GB vRAM"
  hypervisor                = "VMware"
  source_iso                = "9d3595ff-4459-4708-b10b-2fb9c820cab7"
  ssh_username              = "ubuntu"
  ssh_password              = "XXX"
  ssl_no_verify             = "true"
  template_display_text     = "Ubuntu 20.04.3 20060504 010203"
  template_featured         = false
  template_name             = "Ubuntu 20.04.3 Packer"
  template_os               = "Ubuntu 20.04 LTS"
  template_password_enabled = false
  template_scalable         = true
  use_local_ip_address      = "true"
  zone                      = "NL-RTM-RM-G-V-A-R-S-001"
}

build {
  sources = ["source.cloudstack.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "./playbook.yml"
  }
}

### Operating system and Environment details
Ubunto 20.04.3 LTS

### Log Fragments
2022/01/07 11:30:13 Force build: false
2022/01/07 11:30:13 On error: 
2022/01/07 11:30:13 Waiting on builds to complete...
2022/01/07 11:30:13 Starting build run: cloudstack.autogenerated_1
2022/01/07 11:30:13 Running builder: 
2022/01/07 11:30:13 [INFO] (telemetry) Starting builder cloudstack.autogenerated_1
2022/01/07 11:30:13 packer-provisioner-ansible plugin: ansible-playbook version: 2.12.1
==> cloudstack.autogenerated_1: Preparing config...
    cloudstack.autogenerated_1: Config has been prepared!
==> cloudstack.autogenerated_1: Not using a keypair
==> cloudstack.autogenerated_1: Creating instance...
2022/01/07 11:31:46 [INFO] (telemetry) ending cloudstack.autogenerated_1
==> Wait completed after 1 minute 32 seconds
2022/01/07 11:31:46 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2022/01/07 11:31:46 machine readable: cloudstack.autogenerated_1,error []string{"Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64"}
==> Builds finished but no artifacts were created.
2022/01/07 11:31:46 [INFO] (telemetry) Finalizing.
==> cloudstack.autogenerated_1: Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64
==> cloudstack.autogenerated_1: Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64
Build 'cloudstack.autogenerated_1' errored after 1 minute 32 seconds: Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.o
stypeid of type int64

==> Wait completed after 1 minute 32 seconds

==> Some builds didn't complete successfully and had errors:
--> cloudstack.autogenerated_1: Error creating new instance packer-61d82445-ae6f-eb92-11e4-1cddaabe581a: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64

==> Builds finished but no artifacts were created.
2022/01/07 11:31:46 waiting for all plugin processes to complete...
2022/01/07 11:31:46 /home/packer/.config/packer/plugins/github.com/hashicorp/cloudstack/packer-plugin-cloudstack_v1.0.0_x5.0_linux_amd64: plugin process exited
2022/01/07 11:31:46 /usr/bin/packer: plugin process exited

**Comment by ellingtonsantos** [comment]
I have same problem: packer 1.7.10 and cloudstack 4.11.3.0

**Comment by tenvecera** [comment]
Same here: packer 1.7.10 and cloudstack 4.15.2. I'm wonder if isn't problem old cloudstack client. If I understand well it's used this sdk: [https://github.com/xanzy/go-cloudstack](https://github.com/xanzy/go-cloudstack), but I don't know which version. BTW is here reason to not use apache go sdk [https://github.com/apache/cloudstack-go](https://github.com/apache/cloudstack-go)?

**Comment by tenvecera** [comment]
Ok, xanzy/go-cloudstack is archived and now should be used apache/cloudstack-go. So I try it in version v2.12.0 and it's just works. Should I do pull request or is this project dead? This project use archived sdk in really old version v2.4.1 even on xanzy repository is version v2.9.0.

**Comment by ellingtonsantos** [comment]
Please, make a PR and we pray together for a merge.
